import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const collectionsDir = path.join(__dirname, 'public', 'collections');
const outputFile = path.join(__dirname, 'src', 'data', 'collectionsData.js');

if (!fs.existsSync(path.dirname(outputFile))) {
    fs.mkdirSync(path.dirname(outputFile), { recursive: true });
}

const PRODUCTS = [];
let idCounter = 1;

if (fs.existsSync(collectionsDir)) {
    const folders = fs.readdirSync(collectionsDir).filter(f => fs.statSync(path.join(collectionsDir, f)).isDirectory());

    folders.forEach(folderName => {
        const folderPath = path.join(collectionsDir, folderName);
        const files = fs.readdirSync(folderPath);

        // Group into pairs: thumb and large image
        // Usually: aether-0001-thumb.jpg and aether-0001.JPG
        // Wait, looking at aether: "aether-0001-thumb.jpg", "aether-0001.JPG"
        const variantsMap = new Map();

        files.forEach(file => {
            if (!file.match(/\.(jpg|jpeg|png|webp)$/i)) return;

            const isThumb = file.toLowerCase().includes('-thumb');
            const baseNameMatch = file.match(/^(.*?)(?:-thumb)?\.(jpg|jpeg|png|webp)$/i);

            if (baseNameMatch) {
                const baseKey = baseNameMatch[1].toLowerCase();
                if (!variantsMap.has(baseKey)) {
                    variantsMap.set(baseKey, { thumb: null, large: null });
                }

                const entry = variantsMap.get(baseKey);
                if (isThumb) {
                    entry.thumb = `/collections/${folderName}/${file}`;
                } else {
                    entry.large = `/collections/${folderName}/${file}`;
                }
            }
        });

        // Convert map to variants array
        const variants = [];
        variantsMap.forEach((val, key) => {
            if (val.thumb || val.large) {
                // If it's missing a thumb, fallback to large, and vice versa
                variants.push({
                    name: key.split('-').map(part => part.charAt(0).toUpperCase() + part.slice(1)).join(' '),
                    img: val.thumb || val.large,
                    lifestyleImg: val.large || val.thumb // Let's use large for lifestyle/zoom
                });
            }
        });

        if (variants.length > 0) {
            // Sort variants by name purely for consistency
            variants.sort((a, b) => a.name.localeCompare(b.name));

            PRODUCTS.push({
                id: idCounter++,
                name: folderName,
                category: 'Designer Collection', // Dummy category for now
                color: 'Multiple Variants',
                backing: 'Acoustic Base', // Dummy default 
                img: variants[0].img,
                lifestyleImg: variants[0].lifestyleImg,
                variants: variants,
                specs: [
                    { key: 'Construction', value: 'Loop Pile' },
                    { key: 'Fiber Composition', value: '100% Nylon (Polyamide 6)' },
                    { key: 'Yarn Type', value: 'BCF' },
                    { key: 'Dye Method', value: 'Solution Dyed' },
                    { key: 'Pile Weight', value: '700 g/m²' },
                    { key: 'Tile Size', value: '50 cm × 50 cm' },
                    { key: 'Total Height', value: '7.50 mm' },
                ] // basic specs
            });
        }
    });
}

const fileContent = `// Automatically generated by generateCollectionsData.js

export const PRODUCTS = ${JSON.stringify(PRODUCTS, null, 2)};
`;

fs.writeFileSync(outputFile, fileContent, 'utf-8');
console.log(`Generated ${PRODUCTS.length} collections into src/data/collectionsData.js!`);
